"""
fasapi/schemas/integrations_schema.py
--------------------------------------
Pydantic models for the /integrations endpoints.
"""
from pydantic import BaseModel, Field


class GithubTokenRequest(BaseModel):
    github_token: str = Field(..., description="GitHub Personal Access Token (PAT).")


class GmailTokenRequest(BaseModel):
    gmail_token_json: str = Field(
        ...,
        description=(
            "Full Gmail OAuth token JSON string. "
            "This is the contents of your local token.json file generated by auth_gmail.py."
        ),
    )


class IntegrationStatusResponse(BaseModel):
    github_connected: bool
    gmail_connected: bool
